### ISSUE TITLE
您有联系方式吗？

### ISSUE THREAD

**Issue by ghost** [pi314/scp-foundation#19]

**Comment by pi314** [comment]
@SourcePowered: 你好~ 我並不是專業，甚至也不算是業餘的翻譯者，翻譯這些只是因為喜歡這些故事。日前碩班剛畢業，接下來要準備工作，估計沒什麼時候繼續進行，不過這裡的譯本都可以自由取用，祝你的 SCP 分部開展順利~

**Comment by SourcePowered** [comment]
@pi314 我也不是專業的，可是捐捐細流，彙成江河，不是嗎？目前我自己壹個人慢慢的在搬運那2999條。。。我真的需要幫助……我對于繁體中文的理解不是特別好，因此……如果您方便的話，就提供壹下聯系方式吧。

**Comment by SourcePowered** [comment]
我們收購了壹個域名，http://scp.wiki，現正在進行准備工作，我們真的需要像您這樣的懂繁體中文的朋友。

**Comment by iblislin** [comment]
https://github.com/iblis17/scp4tw 如果這個有幫助話。
